# General configuration
general:
  start_date: "2022-01-01"
  end_date: "2022-12-31"
  ticker: "AAPL"
  
# ARIMA model configuration
arima:
  order: [1, 1, 1]

# SARIMA model configuration
sarima:
  order: [1, 1, 1]
  seasonal_order: [1, 1, 1, 12]

# LSTM model configuration
lstm:
  epochs: 50
  batch_size: 32
  learning_rate: 0.001
  hidden_units: 50

# Data processing parameters
data_processing:
  scale_features: ["Close", "Volume"]

# Portfolio optimization
portfolio:
  target_return: 0.1
  risk_tolerance: 0.05

# Paths
paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  model_output: "models/"
